package Entities.Enums.Lexer;

public enum TokenType
{
    DOT,
    EOF,
    TYPE,
    COLON,
    COMMA,
    EQUALS,
    RETURN,
    DECLARE,
    CONSTANT,
    FUNCTION,
    SEMICOLON,
    IDENTIFIER,
    OPEN_BRACE,
    CLOSE_BRACE,
    OPEN_BRACKETS,
    FLOAT_LITERAL,
    CLOSE_BRACKETS,
    STRING_LITERAL,
    INTEGER_LITERAL,
    BINARY_OPERATOR,
    OPEN_PARENTHESIS,
    CLOSE_PARENTHESIS,
}
